version: '3'
services:

  simple_web_app:
    container_name: simple_web_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./httpd.conf:/etc/httpd/conf/httpd.conf
    command: sh -c '/usr/sbin/httpd -D FOREGROUND'
